### ISSUE TITLE
imagePullSecrets template wrong format

### ISSUE THREAD

**Issue by zm1990s** [avinetworks/avi-helm-charts#114]
In statefulset.yaml line 19~21,  imagePullSecrets's value is wrong, it should be  `- name: {{  toYaml . }}`
```
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
```

Fix:
```
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{  toYaml . }}
    {{- end }}
```

**Comment by sudswasavi** [comment]
hi @zm1990s If you'd still like someone to take a look at this issue, can you pls file this issue here: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes ? We would be retiring this repo soon in favour of the source code repo.

**Comment by zm1990s** [comment]
Moved to https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/issues/589
