### ISSUE TITLE
Image tag should be overridable

### ISSUE THREAD

**Issue by carpenterm** [avinetworks/avi-helm-charts#154]
In the AKO chart the image tag is hard coded: 

```
image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
```

We rebuild all of our open source images in our own repository and apply a build date suffix. We can't use the chart as it is without modifying it.

Standard practice is to allow the image tag to be overridden and have the image tag supplied in the default values.yaml file. Like this:

```
image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

**Comment by sudswasavi** [comment]
Hi @carpenterm could you pls file this issue on https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes - or I could do it on your behalf. We will be retiring this repo soon in favour of the source code repo being the only place for all these issues/documentation.

**Comment by carpenterm** [comment]
Done!
